
package ar.com.decidir.api.operation.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OperationPortType", targetNamespace = "urn:Decidir.net")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ar.com.decidir.api.operation.service.ObjectFactory.class,
    org.wso2.ws.dataservice.ObjectFactory.class
})
public interface OperationPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns net.decidir.Operations
     * @throws DataServiceFault
     */
    @WebMethod(operationName = "Get", action = "urn:Get")
    @WebResult(name = "Operations", targetNamespace = "urn:Decidir.net", partName = "parameters")
    public Operations get(
        @WebParam(name = "Get", targetNamespace = "urn:Decidir.net", partName = "parameters")
        Get parameters)
        throws DataServiceFault
    ;

}
