
package ar.com.decidir.api.authorize.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AuthorizePortType", targetNamespace = "http://api.decidir.com.ar")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AuthorizePortType {


    /**
     * Service definition of Operation GetAuthorizeAnswer: Utilizada para recuerar los datos de la Respuesta de la Autorizacion en el Caso de Clientes no PCI
     * 
     * @param parameters
     * @return
     *     returns ar.com.decidir.api.GetAuthorizeAnswerResponse
     */
    @WebMethod(operationName = "GetAuthorizeAnswer")
    @WebResult(name = "GetAuthorizeAnswerResponse", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
    public GetAuthorizeAnswerResponse getAuthorizeAnswer(
        @WebParam(name = "GetAuthorizeAnswer", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
        GetAuthorizeAnswer parameters);

    /**
     * Service definition of Operation SendAuthorizeRequest: Utilizada para enviar los datos que se utilizaran en el  requerimiento de Autorizacion, para Clientes PCI
     * 
     * @param parameters
     * @return
     *     returns ar.com.decidir.api.SendAuthorizeRequestResponse
     */
    @WebMethod(operationName = "SendAuthorizeRequest")
    @WebResult(name = "SendAuthorizeRequestResponse", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
    public SendAuthorizeRequestResponse sendAuthorizeRequest(
        @WebParam(name = "SendAuthorizeRequest", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
        SendAuthorizeRequest parameters);

    /**
     * Service definition of Operation Authorize: Utilizada para enviar el requerimiento de Autorizacion para Clientes PCI 
     * 
     * @param parameters
     * @return
     *     returns ar.com.decidir.api.ExecuteResponse
     */
    @WebMethod(operationName = "Execute")
    @WebResult(name = "ExecuteResponse", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
    public ExecuteResponse execute(
        @WebParam(name = "Execute", targetNamespace = "http://api.decidir.com.ar", partName = "parameters")
        Execute parameters);

}
